matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libboost-dev
            - libjpeg-dev
            - libqt4-dev
            - libpng-dev
            - libtiff-dev
            - libboost-all-dev
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libboost-dev
            - libjpeg-dev
            - libqt4-dev
            - libpng-dev
            - libtiff-dev
            - libboost-all-dev
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libboost-dev
            - libjpeg-dev
            - libqt4-dev
            - libpng-dev
            - libtiff-dev
            - libboost-all-dev
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libboost-dev
            - libjpeg-dev
            - libqt4-dev
            - libpng-dev
            - libtiff-dev
            - libboost-all-dev
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libboost-dev
            - libjpeg-dev
            - libqt4-dev
            - libpng-dev
            - libtiff-dev
            - libboost-all-dev
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - os: linux
      dist: focal
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - libboost-dev
            - libjpeg-dev
            - libqt4-dev
            - libpng-dev
            - libtiff-dev
            - libboost-all-dev
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
      before_install:
        - sudo add-apt-repository -y ppa:rock-core/qt4
        - sudo apt-get -q update
        - sudo apt-get -y install libqt4-dev

before_install:
  - eval "${MATRIX_EVAL}"

language: c++
script:
  - cmake .
  - make